### ISSUE TITLE
JSE 12 compatibility issue with : sun.reflect.Reflection

### ISSUE THREAD

**Issue by fdaugan** [ligoj/plugin-id-ldap-embedded#2]
Embedded LDAP server produces this error at startup:
```
Caused by: java.lang.ClassNotFoundException: sun.reflect.Reflection
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at org.apache.directory.server.core.avltree.ArrayMarshaller.deserialize(ArrayMarshaller.java:153) ~[apacheds-core-avl-1.5.5.jar:?]
	at org.apache.directory.server.core.avltree.ArrayMarshaller.deserialize(ArrayMarshaller.java:43) ~[apacheds-core-avl-1.5.5.jar:?]
	at org.apache.directory.server.core.partition.impl.btree.jdbm.JdbmTable.getDupsContainer(JdbmTable.java:988) ~[apacheds-jdbm-store-1.5.5.jar:?]
	at org.apache.directory.server.core.partition.impl.btree.jdbm.JdbmTable.get(JdbmTable.java:382) ~[apacheds-jdbm-store-1.5.5.jar:?]
	at org.apache.directory.server.core.partition.impl.btree.jdbm.JdbmIndex.forwardLookup(JdbmIndex.java:436) ~[apacheds-jdbm-store-1.5.5.jar:?]
	at org.apache.directory.server.core.partition.impl.btree.jdbm.JdbmStore.getEntryId(JdbmStore.java:904) ~[apacheds-jdbm-store-1.5.5.jar:?]
	at org.apache.directory.server.xdbm.search.impl.DefaultSearchEngine.cursor(DefaultSearchEngine.java:99) ~[apacheds-xdbm-search-1.5.5.jar:?]
	at org.apache.directory.server.core.partition.impl.btree.BTreePartition.search(BTreePartition.java:243) ~[apacheds-core-1.5.5.jar:?]
	at org.apache.directory.server.core.schema.SchemaPartitionDao.listSchemas(SchemaPartitionDao.java:208) ~[apacheds-core-1.5.5.jar:?]
	at org.apache.directory.server.core.schema.SchemaPartitionDao.getSchemas(SchemaPartitionDao.java:168) ~[apacheds-core-1.5.5.jar:?]
	at org.apache.directory.server.core.DefaultDirectoryService.initialize(DefaultDirectoryService.java:1548) ~[apacheds-core-1.5.5.jar:?]
	at org.apache.directory.server.core.DefaultDirectoryService.startup(DefaultDirectoryService.java:971) ~[apacheds-core-1.5.5.jar:?]
	... suppressed 2 lines
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845) ~[spring-beans-5.3.6.jar:5.3.6]
```

**Comment by fdaugan** [comment]
Related to https://github.com/spring-projects/spring-security/issues/6804

Add this to the pom :
```
<dependencyManagement>
<dependencies>
	<dependency>
		<groupId>org.apache.directory.server</groupId>
		<artifactId>apacheds-core-avl</artifactId>
		<!-- Needed for JSE12+ compatibility -->
		<version>1.5.7</version>
	</dependency>
</dependencies>
</dependencyManagement>
```
